In [3]:
#Etapa 2 — Carregar a base

import pandas as pd

dados = pd.read_csv("dados_original.csv", sep=";")

In [4]:
#Etapa 3 — Verificar estrutura
dados.head()

,id_turma,turma,escola,projeto,categoria,curso,modalidade,qtde_vagas,turno,data_inicio,data_fim,status_turma,carga_horaria,matriculas_turma,matriculas_aptas
0,5575,QP-ABF-PMU-V2-2022,EM ARTES BASILEU FRANÇA,01 - EFGS - ESCOLAS DO FUTURO DO ESTADO DE GOIÁS,Qualificação,PERFORMANCE MUSICAL,PRESENCIAL,23,VESPERTINO,14/02/2022,28/06/2024,Concluído,126,23,11
1,5535,TEC-ABF-MIM-N1-2022,EM ARTES BASILEU FRANÇA,01 - EFGS - ESCOLAS DO FUTURO DO ESTADO DE GOIÁS,Técnico,TÉCNICO DE NÍVEL MEDIO EM INSTRUMENTO MUSICAL,PRESENCIAL,22,NOTURNO,17/02/2020,30/06/2024,Concluído,267,17,11
2,5534,TEC-ABF-MIM-V1-2022,EM ARTES BASILEU FRANÇA,01 - EFGS - ESCOLAS DO FUTURO DO ESTADO DE GOIÁS,Técnico,TÉCNICO DE NÍVEL MEDIO EM INSTRUMENTO MUSICAL,PRESENCIAL,22,VESPERTINO,26/05/2021,14/08/2024,Concluído,235,17,15
3,5472,CP-JLB-MKTDG-ONL-N3-2022,JOSÉ LUIZ BITTENCOURT,01 - EFGS - ESCOLAS DO FUTURO DO ESTADO DE GOIÁS,Capacitação,MARKETING DIGITAL - ONL,PRESENCIAL,34,NOTURNO,29/06/2022,13/07/2022,Concluído,23,34,25
4,5470,QP-SLLKO-QPIMNI-N1-2022,SARAH LUÍSA LEMOS KUBITSCHEK DE OLIVEIRA,05 - ROJG - REDE DE ORQUESTRA JOVEM DE GOIÁS,Qualificação,QUALIFICAÇÃO PROFISSIONAL EM INSTRUMENTO MUSIC...,PRESENCIAL,28,NOTURNO,20/06/2022,23/12/2022,Concluído,134,28,28

In [5]:
dados.shape

(5157, 15)

In [6]:
dados.columns

Index(['id_turma', 'turma', 'escola', 'projeto', 'categoria', 'curso',
       'modalidade', 'qtde_vagas', 'turno', 'data_inicio', 'data_fim',
       'status_turma', 'carga_horaria', 'matriculas_turma',
       'matriculas_aptas'],
      dtype='object')

In [7]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5157 entries, 0 to 5156
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_turma          5157 non-null   int64
 1   turma             5157 non-null   object
 2   escola            5157 non-null   object
 3   projeto           5157 non-null   object
 4   categoria         5157 non-null   object
 5   curso             5157 non-null   object
 6   modalidade        5157 non-null   object
 7   qtde_vagas        5157 non-null   int64
 8   turno             5157 non-null   object
 9   data_inicio       5157 non-null   object
 10  data_fim          5157 non-null   object
 11  status_turma      5157 non-null   object
 12  carga_horaria     5157 non-null   object
 13  matriculas_turma  5157 non-null   int64
 14  matriculas_aptas  5157 non-null   object
dtypes: int64(3), object(12)
memory usage: 604.5+ KB

In [8]:
#Etapa 4 — Verificar valores ausentes
dados.isnull().sum()

id_turma            0
turma               0
escola              0
projeto             0
categoria           0
curso               0
modalidade          0
qtde_vagas          0
turno               0
data_inicio         0
data_fim            0
status_turma        0
carga_horaria       0
matriculas_turma    0
matriculas_aptas    0
dtype: int64

In [9]:
#Etapa 5 — Verificar duplicidades
dados.duplicated().sum()

np.int64(1904)

In [10]:
dados[dados.duplicated()]

,id_turma,turma,escola,projeto,categoria,curso,modalidade,qtde_vagas,turno,data_inicio,data_fim,status_turma,carga_horaria,matriculas_turma,matriculas_aptas
647,5575,QP-ABF-PMU-V2-2022,EM ARTES BASILEU FRANÇA,01 - EFGS - ESCOLAS DO FUTURO DO ESTADO DE GOIÁS,Qualificação,PERFORMANCE MUSICAL,PRESENCIAL,23,VESPERTINO,14/02/2022,28/06/2024,Concluído,126,23,11
684,5535,TEC-ABF-MIM-N1-2022,EM ARTES BASILEU FRANÇA,01 - EFGS - ESCOLAS DO FUTURO DO ESTADO DE GOIÁS,Técnico,TÉCNICO DE NÍVEL MEDIO EM INSTRUMENTO MUSICAL,PRESENCIAL,22,NOTURNO,17/02/2020,30/06/2024,Concluído,267,17,11
685,5534,TEC-ABF-MIM-V1-2022,EM ARTES BASILEU FRANÇA,01 - EFGS - ESCOLAS DO FUTURO DO ESTADO DE GOIÁS,Técnico,TÉCNICO DE NÍVEL MEDIO EM INSTRUMENTO MUSICAL,PRESENCIAL,22,VESPERTINO,26/05/2021,14/08/2024,Concluído,235,17,15
741,5472,CP-JLB-MKTDG-ONL-N3-2022,JOSÉ LUIZ BITTENCOURT,01 - EFGS - ESCOLAS DO FUTURO DO ESTADO DE GOIÁS,Capacitação,MARKETING DIGITAL - ONL,PRESENCIAL,34,NOTURNO,29/06/2022,13/07/2022,Concluído,23,34,25
743,5470,QP-SLLKO-QPIMNI-N1-2022,SARAH LUÍSA LEMOS KUBITSCHEK DE OLIVEIRA,05 - ROJG - REDE DE ORQUESTRA JOVEM DE GOIÁS,Qualificação,QUALIFICAÇÃO PROFISSIONAL EM INSTRUMENTO MUSIC...,PRESENCIAL,28,NOTURNO,20/06/2022,23/12/2022,Concluído,134,28,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5148,6885,TEC-LR-DWC-C-I5-2024,LUIZ RASSI,JORNADA PARA O FUTURO,Técnico,TÉCNICO EM DESENVOLVIMENTO WEB E CIBERSEGURANÇA,PRESENCIAL,25,INTEGRAL,22/01/2024,-,Cancelado,569,2,-
5149,6884,TEC-LR-DWC-C-I4-2024,LUIZ RASSI,JORNADA PARA O FUTURO,Técnico,TÉCNICO EM DESENVOLVIMENTO WEB E CIBERSEGURANÇA,PRESENCIAL,30,INTEGRAL,22/01/2024,-,Cancelado,682,4,-
5150,6883,TEC-LR-DWC-C-I3-2024,LUIZ RASSI,JORNADA PARA O FUTURO,Técnico,TÉCNICO EM DESENVOLVIMENTO WEB E CIBERSEGURANÇA,PRESENCIAL,25,INTEGRAL,22/01/2024,-,Cancelado,1053,44,-
5151,6882,TEC-LR-DWC-C-I2-2024,LUIZ RASSI,JORNADA PARA O FUTURO,Técnico,TÉCNICO EM DESENVOLVIMENTO WEB E CIBERSEGURANÇA,PRESENCIAL,56,INTEGRAL,22/01/2024,-,Em Andamento,1406,55,-
5153,6834,SUP-ABF-STPC-N1-2024,EM ARTES BASILEU FRANÇA,01 - EFGS - ESCOLAS DO FUTURO DO ESTADO DE GOIÁS,Graduação,SUPERIOR DE TECNOLOGIA EM PRODUÇÃO CÊNICA,PRESENCIAL,20,NOTURNO,04/03/2024,30/06/2026,Concluído,279,26,28

In [11]:
#Etapa 6 — Verificar os textos
dados.describe(include='object')

,turma,escola,projeto,categoria,curso,modalidade,turno,data_inicio,data_fim,status_turma,carga_horaria,matriculas_aptas
count,5157,5157,5157,5157,5157,5157,5157,5157,5157,5157,5157,5157
unique,3148,34,14,4,947,2,4,674,672,4,424,69
top,TEC-JLB-APRMQ-N1-2022,EM ARTES BASILEU FRANÇA,01 - EFGS - ESCOLAS DO FUTURO DO ESTADO DE GOIÁS,Qualificação,TÉCNICO EM DESENVOLVIMENTO WEB E CIBERSEGURANÇA,PRESENCIAL,VESPERTINO,21/02/2022,-,Concluído,20,-
freq,7,2334,3616,2341,201,4966,1752,277,1016,4141,456,1016

In [12]:
#Etapa 7 — Verificar tipos
dados.dtypes

id_turma             int64
turma               object
escola              object
projeto             object
categoria           object
curso               object
modalidade          object
qtde_vagas           int64
turno               object
data_inicio         object
data_fim            object
status_turma        object
carga_horaria       object
matriculas_turma     int64
matriculas_aptas    object
dtype: object

In [16]:
#20. CRIANDO A BASE TRATADA


# Converter as colunas para o tipo data
dados["data_inicio"] = pd.to_datetime(
    dados["data_inicio"],
    errors="coerce",
    dayfirst=True
)

dados["data_fim"] = pd.to_datetime(
    dados["data_fim"],
    errors="coerce",
    dayfirst=True
)

# Verificar os tipos de dados
print(dados[["data_inicio", "data_fim"]].dtypes)

# Visualizar as datas convertidas
display(dados[["data_inicio", "data_fim"]].head())

# Converter as datas para o formato brasileiro
dados["data_inicio"] = pd.to_datetime(
    dados["data_inicio"], errors="coerce", dayfirst=True
).dt.strftime("%d/%m/%Y")

dados["data_fim"] = pd.to_datetime(
    dados["data_fim"], errors="coerce", dayfirst=True
).dt.strftime("%d/%m/%Y")

# Visualizar as datas
display(dados[["data_inicio", "data_fim"]].head())

# Converter as colunas para números inteiros
dados["carga_horaria"] = pd.to_numeric(
    dados["carga_horaria"], errors="coerce"
).astype("Int64")

dados["matriculas_aptas"] = pd.to_numeric(
    dados["matriculas_aptas"], errors="coerce"
).astype("Int64")

# Verificar os tipos de dados
print(dados[["carga_horaria", "matriculas_aptas"]].dtypes)

# Visualizar os dados
display(dados[["carga_horaria", "matriculas_aptas"]].head())

data_inicio    datetime64[ns]
data_fim       datetime64[ns]
dtype: object

  data_inicio   data_fim
0  2022-02-14 2024-06-28
1  2020-02-17 2024-06-30
2  2021-05-26 2024-08-14
3  2022-06-29 2022-07-13
4  2022-06-20 2022-12-23

  data_inicio    data_fim
0  14/02/2022  28/06/2024
1  17/02/2020  30/06/2024
2  26/05/2021  14/08/2024
3  29/06/2022  13/07/2022
4  20/06/2022  23/12/2022

carga_horaria       Int64
matriculas_aptas    Int64
dtype: object

   carga_horaria  matriculas_aptas
0            126                11
1            267                11
2            235                15
3             23                25
4            134                28

In [19]:
#Criando uma cópia dos dados tratados

dados_tratados = dados.copy()

dados_tratados.to_csv( "dados_tratados.csv", index=False)

In [27]:
#21. CONFERÊNCIA FINAL

print("=" * 45)
print("CONFERÊNCIA ANTES DO TRATAMENTO")
print("=" * 45)

print("Quantidade de registros:", dados.shape[0])
print("Quantidade de colunas:", dados.shape[1])
print("Total de valores ausentes:",
      dados.isnull().sum().sum())
print("Total de linhas duplicadas:",
      dados.duplicated().sum())

print("\nValores ausentes por coluna:")
print(dados.isnull().sum())

print("\nInformações da base original:")
dados.info()

# ==========================================
# 3. REALIZAR OS TRATAMENTOS
# ==========================================

dados_tratados = dados.copy()

# Substituir o símbolo "-" por valor ausente
dados_tratados = dados_tratados.replace(
    r"^\s*-\s*$",
    pd.NA,
    regex=True
)

# Converter as colunas de data
dados_tratados["data_inicio"] = pd.to_datetime(
    dados_tratados["data_inicio"],
    format="%d/%m/%Y",
    errors="coerce"
)

dados_tratados["data_fim"] = pd.to_datetime(
    dados_tratados["data_fim"],
    format="%d/%m/%Y",
    errors="coerce"
)

# Converter as colunas para inteiro
colunas_inteiras = [
    "carga_horaria",
    "matriculas_aptas"
]

# Converter as datas para o formato brasileiro
for coluna in ["data_inicio", "data_fim"]:
    dados[coluna] = pd.to_datetime(
        dados[coluna],
        errors="coerce",
        dayfirst=True
    ).dt.strftime("%d/%m/%Y")

for coluna in colunas_inteiras:
    dados_tratados[coluna] = pd.to_numeric(
        dados_tratados[coluna],
        errors="coerce"
    ).astype("Int64")

# ==========================================
# 4. CONFERÊNCIA DEPOIS DO TRATAMENTO
# ==========================================

print("\n" + "=" * 45)
print("CONFERÊNCIA DEPOIS DO TRATAMENTO")
print("=" * 45)

print("Quantidade de registros:", dados_tratados.shape[0])
print("Quantidade de colunas:", dados_tratados.shape[1])
print("Total de valores ausentes:",
      dados_tratados.isnull().sum().sum())
print("Total de linhas duplicadas:",
      dados_tratados.duplicated().sum())

print("\nValores ausentes por coluna:")
print(dados_tratados.isnull().sum())

print("\nInformações da base tratada:")
dados_tratados.info()

# ==========================================
# 5. COMPARAÇÃO ANTES X DEPOIS
# ==========================================

comparacao = pd.DataFrame({
    "Antes": [
        dados.shape[0],
        dados.shape[1],
        dados.isnull().sum().sum(),
        dados.duplicated().sum()
    ],
    "Depois": [
        dados_tratados.shape[0],
        dados_tratados.shape[1],
        dados_tratados.isnull().sum().sum(),
        dados_tratados.duplicated().sum()
    ]
}, index=[
    "Quantidade de registros",
    "Quantidade de colunas",
    "Valores ausentes",
    "Duplicidades"
])
display(dados[["data_inicio", "data_fim"]].head())
print("\nCOMPARAÇÃO FINAL:")
display(comparacao)

=============================================
CONFERÊNCIA ANTES DO TRATAMENTO
=============================================
Quantidade de registros: 5157
Quantidade de colunas: 15
Total de valores ausentes: 2042
Total de linhas duplicadas: 1904

Valores ausentes por coluna:
id_turma               0
turma                  0
escola                 0
projeto                0
categoria              0
curso                  0
modalidade             0
qtde_vagas             0
turno                  0
data_inicio            0
data_fim            1016
status_turma           0
carga_horaria         10
matriculas_turma       0
matriculas_aptas    1016
dtype: int64

Informações da base original:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5157 entries, 0 to 5156
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_turma          5157 non-null   int64
 1   turma             5157 non-null   object
 2   escola            5157 non-null   object
 3   projeto           5157 non-null   object
 4   categoria         5157 non-null   object
 5   curso             5157 non-null   object
 6   modalidade        5157 non-null   object
 7   qtde_vagas        5157 non-null   int64
 8   turno             5157 non-null   object
 9   data_inicio       5157 non-null   object
 10  data_fim          4141 non-null   object
 11  status_turma      5157 non-null   object
 12  carga_horaria     5147 non-null   Int64
 13  matriculas_turma  5157 non-null   int64
 14  matriculas_aptas  4141 non-null   Int64
dtypes: Int64(2), int64(3), object(10)
memory usage: 614.5+ KB

=============================================
CONFERÊNCIA DEPOIS DO TRATAMENTO
=============================================
Quantidade de registros: 5157
Quantidade de colunas: 15
Total de valores ausentes: 2042
Total de linhas duplicadas: 1904

Valores ausentes por coluna:
id_turma               0
turma                  0
escola                 0
projeto                0
categoria              0
curso                  0
modalidade             0
qtde_vagas             0
turno                  0
data_inicio            0
data_fim            1016
status_turma           0
carga_horaria         10
matriculas_turma       0
matriculas_aptas    1016
dtype: int64

Informações da base tratada:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5157 entries, 0 to 5156
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_turma          5157 non-null   int64
 1   turma             5157 non-null   object
 2   escola            5157 non-null   object
 3   projeto           5157 non-null   object
 4   categoria         5157 non-null   object
 5   curso             5157 non-null   object
 6   modalidade        5157 non-null   object
 7   qtde_vagas        5157 non-null   int64
 8   turno             5157 non-null   object
 9   data_inicio       5157 non-null   datetime64[ns]
 10  data_fim          4141 non-null   datetime64[ns]
 11  status_turma      5157 non-null   object
 12  carga_horaria     5147 non-null   Int64
 13  matriculas_turma  5157 non-null   int64
 14  matriculas_aptas  4141 non-null   Int64
dtypes: Int64(2), datetime64[ns](2), int64(3), object(8)
memory usage: 614.5+ KB

  data_inicio    data_fim
0  14/02/2022  28/06/2024
1  17/02/2020  30/06/2024
2  26/05/2021  14/08/2024
3  29/06/2022  13/07/2022
4  20/06/2022  23/12/2022

COMPARAÇÃO FINAL:

                         Antes  Depois
Quantidade de registros   5157    5157
Quantidade de colunas       15      15
Valores ausentes          2042    2042
Duplicidades              1904    1904

# **22. ATIVIDADE DE REFLEXÃO**
Depois do tratamento, cada equipe deverá responder:

**1.Quais foram os principais problemas encontrados na base?**\
Os campos campos data_inicio e data_fim não estavam em formato de data, e os campos carga_horaria e matriculas_aptas não estavam como inteiro.

**2.Quais problemas foram corrigidos?**\
Os campos carga_horaria e matriculas_aptas foram corrigidos para Int64 e os campos data_inicio e data_fim foram convertidos para datetime64.

**3.Quais problemas foram mantidos?**\
Campos duplicados ocorrem porque cada dado se refere a uma turma, assim o nome da escola, curso, modalidade, turno, status da turma se repetem várias vezes. Alguns campos como data_fim, status e o status estão preenchidos com "-" devido ao curso não ter iniciado ou ter sido cancelado.

**4.Por que alguns dados não foram alterados?**\
Não encontramos necessidade para alteração.

**5.Algum registro precisou ser removido?**\
Nenhum registro precisou ser removido.

**6.Qual foi a justificativa?**\
Analisamos os dados e não encontramos necessidade de alteração.

**7.A base tratada continua representando a realidade da base original?**\
Sim continua.

**8.A base agora está adequada para responder à pergunta principal do projeto?**\
Está adequada para responder as perguntas do projeto.

## **25. Pergunta Avaliativa**

"Dados limpos significam dados confiáveis?"

Após realizar o tratamento da base, responda:
**Por que uma análise pode apresentar conclusões erradas quando os dados não são
tratados adequadamente?**

Na resposta, o grupo deverá apresentar pelo menos um exemplo encontrado na
própria base do projeto.

**Orientação**

Não basta responder apenas:

"Porque dados errados geram resultados errados."
Explique qual problema foi encontrado, o que foi feito e como isso poderia afetar a
análise.

Resposta:

*Dados limpos não significam automaticamente que os dados são totalmente confiáveis, mas o tratamento dos dados é essencial para que a análise tenha resultados mais corretos. Quando os dados não são tratados adequadamente, podem ocorrer erros nos cálculos, gráficos e interpretações, levando a conclusões equivocadas.*

*Na nossa base, encontramos um problema nas colunas data_inicio e data_fim, que não estavam configuradas no formato de data. Por isso, realizamos a conversão dessas colunas para o formato datetime64. Também tratamos as colunas carga_horaria e matriculas_aptas, convertendo-as para formato numérico adequado. Além disso, substituímos o símbolo "-" por valores ausentes para evitar interpretações incorretas dos dados. Essas correções foram registradas no documento de tratamento da base.*

*Se esses problemas não fossem corrigidos, poderíamos ter resultados errados ao analisar períodos das turmas, calcular cargas horárias ou realizar somatórios e médias de matrículas. Por exemplo, uma coluna com números armazenados como texto poderia impedir cálculos corretos ou gerar estatísticas incorretas, comprometendo as decisões tomadas a partir da análise dos dados. Portanto, o tratamento realizado aumentou a qualidade e a confiabilidade das informações utilizadas no projeto.*